version: 2
jobs:
  build:
    environment:
      HUGO_BUILD_DIR: ~/project/public
    docker:
      - image: cibuilds/hugo:0.88.1
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "Run Hugo"
          command: HUGO_ENV=production hugo --theme=phillycocoaheadtheme -v -d $HUGO_BUILD_DIR
      - run:
          name: "Update apt-get"
          command: sudo apt-get update
      - run:
          name: "Install AWS"
          command: sudo apt-get awscli; aws --version
      - run:
          name: "Deploy to S3 if tests pass and branch is Master"
          command: aws s3 sync $HUGO_BUILD_DIR s3://phillycocoa.org
