version: 2
jobs:
  build:
    environment:
      HUGO_BUILD_DIR: ~/project/public
    docker:
      - image: cibuilds/hugo:0.88.1
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "Run Hugo"
          command: HUGO_ENV=production hugo --theme=phillycocoaheadtheme -v -d $HUGO_BUILD_DIR
      - run:
          name: "Install PIP"
          command: apt-get update; apt-get install -y python python-pip python-dev
      - run:
          name: "Install AWS"
          command: pip install awscli; aws --version
      - run:
          name: "Deploy to S3 if tests pass and branch is Master"
          command: aws s3 sync $HUGO_BUILD_DIR s3://phillycocoa.org
